#!/usr/bin/env python
import json
import re
from itertools import islice
from datetime import datetime

filename = "DevOps_interview_data_set"
url = "https://foo.com/bar"


def matchInfo(r, t):
    mResult = t.match(r)
    res = {}
    if mResult:
        deviceName = mResult.group("deviceName")
        processId = mResult.group("processId")
        processName = mResult.group("processName")
        description = mResult.group("description")
        time = mResult.group("timeWindow")
          startStr = re.match(r'[A-Z].*\s(.*?):', time).groups()[0]
          startTime = datetime.strptime(startStr, "%H")
          end = (int(startStr) + 1) % 24
          endtime = datetime.strptime(str(end), "%H")
        timeWindow = startTime.strftime("%H:%M:%S") + endtime.strftime("%H:%M:%S")
    return ""
   
def prefile(filename):
    list = []
    pattern = re.compile(r'((?P<timeWindow>[A-Z].*?:[0-9]{2}):[0-9]{2}(\s))(?P<deviceName>[\w]+)\s(?P<processName>[\w].*?\[(?P<processId>\d+)\]\)?):\s(?P<description>[\w].*\.)'
    with open(filename) as f:
        while "" in content:
               content.remove("") 
        for line in f:
            if line.endswith(":\n"):
                pattern = re.compile(r'((?P<timeWindow>[A-Z].*?:[0-9]{2}):[0-9]{2}(\s))(?P<deviceName>[\w]+)\s(?P<processName>[\w].*?\[(?P<processId>\d+)\]\)?):\s(?P<description>[\w].*\.)', re.DOTALL)
                mer = line.strip() + " " + " ".join([x.strip() for x in islice(f, 2)])
                info = matchInfo(mer, pattern)
                if info:
                    list.append(info)
            else:
                info = matchInfo(line, pattern)
                if info:
                    list.append(info)
    return list
    
    def occurrence(list):
    occurrenceSum = {}
    for log in list:
        timeWindow = log.get("timeWindow")
        if occurrenceSum.get(timeWindow):
            occurrenceSum[timeWindow] += 1
        else:
            occurrenceSum[timeWindow] = 1
    return occurrenceSum


def main():
    
    list = prefile("DevOps_interview_data_set")
    repeat = occurrence(list)
    list.append(repeat)
    
if __name__ == '__main__':
    req = requests.post(url, data=json.dumps(list))
    print(req)
